apiVersion: v1
kind: PersistentVolume
metadata:
  name: development-wip-api-volume
  labels:
    app: wip-api
    organize: wipcamp10
    tier: backend
    env: development
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.wip.camp
    path: "/mnt/wip-camp/development-api-storage"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: development-wip-api-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      app: wip-api
      organize: wipcamp10
      tier: backend
      env: development